update packages-feed to HEAD of master-branch (20 Jul 2018)
0edd0ee4 Merge pull request #6524 from zhaojh329/libuhttpd
0cb6e15f irqbalance: fix AARCH64 compilation
960dfe24 libuhttpd: Update to 2.1.2
76c48659 Merge pull request #6493 from neheb/patch-5
b5032297 Merge pull request #6440 from neheb/patch-12
06036e96 Merge pull request #6435 from neheb/patch-9
ced36d23 Merge pull request #6518 from Ansuel/uwsgites
a93066b5 uwsgi-cgi: fix compilation on Darwin system
43eaa1b1 Merge pull request #6512 from Ansuel/secureuwsgi
0410c7b2 uwsgi-cgi: set socket to 666 permission
9b327f81 Merge pull request #6508 from jefferyto/slide-switch-0.9.2
756c0f6f slide-switch: update to latest version
3e7c9549 Merge pull request #6485 from Ansuel/nginxfix
841c720f Merge pull request #6501 from stangri/simple-adblock
893f8788 travis: fail on bad hash message
ac34bf91 simple-adblock: better download processing, luci-app integration, lists optimization, firewall integration
9f1f8826 Merge pull request #6469 from micmac1/zdb-nls
6f23ab17 Merge pull request #6475 from diizzyy/patch-4
6132b459 Merge pull request #6467 from micmac1/python-mysql-nls
64ccc26f Merge pull request #6483 from lucize/clamup
b9ee4c3d Merge pull request #6477 from MikePetullo/libsoup
089dd167 Merge pull request #6476 from MikePetullo/libpsl
d29abc18 Merge pull request #6474 from diizzyy/patch-3
74b7fd3e Merge pull request #6486 from MikePetullo/libgcrypt
a7ded795 Merge pull request #6489 from neheb/patch-3
8b58fe43 Merge pull request #6487 from MikePetullo/syslog-ng
9f5f2858 Merge pull request #6472 from MikePetullo/libgpg-error
59dc796c Merge pull request #6482 from lucize/doveup
91c09d2e Merge pull request #6490 from neheb/shine
0c4e9fb1 Merge pull request #6495 from diizzyy/patch-5
d57c63cf Merge pull request #6461 from hbl0307106015/tdb
4a83c48b Merge pull request #6484 from diizzyy/uwsgi-cgi
d3fd6bf6 btrfs-progs: Update to 4.17
061fc104 attr: Switch to tarball releases
d1804d38 tdb: bump to latest version
dd14b2cb shine: Update to 3.1.1
79b4a9b3 libtalloc: Update to 2.1.14
eafc36fb libgcrypt: update to 1.8.3
7e9c044f syslog-ng: update to 3.16.1
4474f91e nginx: make virtual package provide nginx
9eefad0a uwsgi-cgi: General cleanup
99eb143b clamav: update to 0.100.1
06ee5719 dovecot: update to 2.3.2.1
d42e863e Merge pull request #6425 from micmac1/dovecot-uclibc-iconv
3d4c3c32 Merge pull request #6424 from micmac1/collectd-uclibc-iconv
fdf7a9d1 Merge pull request #6466 from Ansuel/nginxfix
651d0a23 tor: update to 0.3.3.9
7901fd3f pulseaudio:   * update to 12.1   * cleanup Makefile
b2ba4a2e libgpg-error: update to 1.32
df91a9cc libsoup: update to 2.63.2
779cc8ea libpsl: add new package
bc381700 utils/tio: Update to 1.31
77ec669b utils/fio: Update to 3.7
34e67aa8 libhttp-parser: Update to 2.8.1
433e0fe7 nginx: fix bug in uci-defaults scripts
b25b0fc2 libzdb: remove iconv hack, include nls.mk
7cfabe8d python-mysql: include nls.mk, remove hack
b695c115 collectd: include nls.mk for mysql plugin
1ec6d2be dovecot: include nls.mk for iconv support
3fdef4e2 Merge pull request #6463 from micmac1/mariadb-nls
3297b45a Merge pull request #6465 from OldKosherCheese/mymaster
23b7d14b python3: fix libuuid missing dependency for python3-light
5dd920e0 mariadb: use nls.mk for consistent iconv handling
2794a18b Merge pull request #6392 from sartura/geth
666602f7 Merge pull request #6411 from crza/update-python
3ec9fc2f Merge pull request #6428 from cshoredaniel/pr-deprecate-msmtp-scripts
2080550f python3: add override for uuid.h header check
fe01c8fc python3: update to python 3.7.0 Fixes python3 host SSL build -> host-pip can use https:// urls again. Updates Pip to 10.0.1 rebased patches
01981140 Merge pull request #6256 from neheb/patch-17
8aba46bd Merge pull request #6430 from neheb/patch-2
8338eebb Merge pull request #6432 from neheb/patch-5
e2ccada5 Merge pull request #6456 from salzmdan/master
6b028771 Merge pull request #6454 from MikePetullo/luafilesystem
64679fb2 Merge pull request #6449 from MikePetullo/vips
bc17c7e2 Merge pull request #6447 from MikePetullo/pigeonhole
e146db29 Merge pull request #6433 from MikePetullo/gst1-plugins-good
99c084d3 knot: update to 2.6.8
d12b9f7d Merge pull request #6436 from neheb/patch-10
97c756f7 luafilesystem: update to 1.7.0.2
2e82a6bb vips: update to 8.6.4
525748f7 libradcli: Update to 1.2.10
315d6780 Merge pull request #6165 from Rixerx/master
46388f1c pigeonhole: update to 0.5.2
ceb2daec Merge pull request #6426 from Ansuel/nginxbump
6365c1aa Merge pull request #6427 from Ansuel/uwsgiupdate
2dfdccfc Merge pull request #6434 from neheb/patch-7
cde67fb8 Merge pull request #6437 from MikePetullo/gst1-plugins-bad
b4be4b2c Merge pull request #6438 from MikePetullo/gst1-libav
7cdb28ab Merge pull request #6441 from neheb/patch-14
9364a3ba radsecproxy: bump to 1.7.1
f1248985 Merge pull request #6431 from neheb/patch-3
899c3c31 uwsgi-cgi: bump to latest release
6f5fe22b Merge pull request #6445 from EricLuehrsen/unbound_20180709_doc
0d8159f5 unbound: add README recipe for DNS/TLS outside of UCI
5eb07af2 treewide: add missing mirror hash
121b10b2 nginx: allow make check to fixup mirror hash
79e977a2 nginx: add config symbols of rtmp,ts to PKG_CONFIG_DEPENDS
77c2de7f uwsgi-cgi: fix libcap detection
19bde8da libsoc: fix compilation error caused by multiple goals on make
77519979 libantlr3c: Update to 3.4
a159d999 gst1-libav: update to 1.14.1
9cffc42d gst1-plugins-bad: update to 1.14.1
7b5c0026 libxerces-c: Update to 3.2.1
89ea5754 libtalloc: Update to 2.1.13
d7c9e24b gst1-plugins-good: build lame and mpg123 plugins, which moved from ugly
4e98ac0c gptfdisk: Update to 1.0.4
51b672df xmlrpc-c: Update to 1.39.13
85c38f59 yaml:  Update to 0.2.1
21bef99c Merge pull request #6429 from MikePetullo/gst1-plugins-ugly
d6b25013 gst1-plugins-ugly: update to 1.14.1
79a876df mail/msmtp-scripts: Deprecated upstream; remove myself as maintainer
d42df123 nginx: bump to latest release
fe6e002e Merge pull request #6421 from micmac1/gnunet-uclibc-iconv
749029c1 Merge pull request #6422 from micmac1/libzdb-uclibc-iconv
acc59d3a gnunet: fix uclibc build issue
bc034d58 Merge pull request #6419 from micmac1/python-mysql-404
a7ec2bf3 Merge pull request #6418 from micmac1/mariadb-uclibc
9c7613dd libzdb: fix uclibc build issue
230bfc96 python-mysql: fix uclibc build failure
9d236132 python-mysql: fix download URL
5702078d mariadb: fix uClibc builds
f7272222 mariadb: fix CPPFLAGS handling
b33ec70c utils/collectd: run with low priority
e63960f2 Merge pull request #6417 from MikePetullo/gst1-plugins-good
2f916332 Merge pull request #6416 from MikePetullo/gst1-plugins-base
1fcdb2cf Merge pull request #6415 from MikePetullo/gstreamer1
c1eae5d2 gst1-plugins-good: update to 1.14.1
92b385c2 gst1-plugins-base: update to 1.14.1
966f07c8 gstreamer1: update to 1.14.1
2aba3ab9 Merge pull request #6414 from tru7/libfmt
96101ff8 libfmt: bump to new release 5.1.0
e9cdac56 Merge pull request #6229 from sartura/dhcpcd_bump_to_7.0.5
1d5d6e6f Merge pull request #5646 from neheb/libnet
831142a7 Merge pull request #6313 from neheb/sispmctl
e28f1bc7 Merge pull request #6365 from neheb/patch-3
5a27e1c4 Merge pull request #6202 from cotequeiroz/seafile_openssl-1.1
cee70880 libnet: Change PKG_SOURCE_URL to use @SF macro.
0545484f Merge pull request #6279 from neheb/patch-19
fcdcc328 Merge pull request #6270 from neheb/patch-24
2a141f00 sispmctl: Update to 4.0
4c2775c2 Merge pull request #6251 from neheb/patch-12
3a0f4fe8 Merge pull request #6249 from neheb/patch-10
c7c40703 fdm: Switch to GitHub releases.
f42a51ae Merge pull request #6230 from sartura/sysstat_bump_to_11.6.4
25aee63d Merge pull request #6221 from neheb/patch-5
70a32988 Merge pull request #6218 from neheb/patch-2
5bbbc36b Merge pull request #6216 from neheb/patch-7
5ae519b7 Merge pull request #6407 from lucize/doveup
78b842da dovecot: update to 2.3.2
b7f71c69 php7: fix load order of mysqli extension
dd76c9c1 Merge pull request #6245 from neheb/patch-9
d222edcf Merge pull request #6280 from neheb/zmq
4eda8081 Merge pull request #6332 from micmac1/mysql-python-up
85c96dda Merge pull request #6393 from yangfl/master
63ce209d Merge pull request #6406 from MikePetullo/krb5
a81df2bc Merge pull request #6383 from thess/add-nasm
346925a2 Merge pull request #6328 from Ansuel/reworknginx
c351abec nginx: bump and add build variant and other fix
8256b967 krb5: update to 1.16.1
8e6a40ae geth: add a new package
d0cc437f rsync: Add IPv6 functionality
b4a3ac3d dmapd: update to 0.0.75
ebeb0607 libdmapsharing: update to 3.9.1
3bcaa7a4 protobuf-c: bump to 1.3.0
c9a9f6f9 luasql: fix compile with mariadb-10.2.x
4b9ec8db libwebsockets: Update to 3.0.0
b9cfb7f3 i2c-tools: fix stale PKG_SOURCE_URL
920df550 Merge pull request #6358 from sartura/sysrepo-release-0.7.4
ea3acfe6 Merge pull request #6400 from cshoredaniel/pr-cshoredaniel-maintainer-changes
d93d21a0 gnupg: Remove myself as maintainer
d35e0eaf findutils: Remove myself as maintainer
eb13e5b3 msmtp-scripts: Update my email
b4fe49d2 nut: Update my email
5de5ac2a gitolite: Update my email
6aac16b1 rp-pppoe: Remove myself as maintainer
4a5c3dc7 Merge pull request #6288 from sdelafond/diffutils_x86
f84ac71b Merge pull request #6301 from micmac1/mariadb-up-102
3ab201cc Merge pull request #6309 from diizzyy/patch-2
d1952a7b Merge pull request #6340 from gladiac1337/feature-haproxy-v1.8.10
afe2038f i2pd: Update to 2.19.0
86106ecb i2pd: Move DATADIR to /var/lib/i2pd, fix #5693
9ce4d519 node: bump to 8.11.3
fc3beffe travis: don't need git cloning progress
54121977 Merge pull request #6389 from pprindeville/perl-text-csv_xs-update-1.36
045fdb53 php7: update to 7.2.7
3b45e955 vim: disable darwin support
ed44e02f sysrepo: update to 0.7.4
ba647c04 netopeer2: update to 0.5.26
1a910ebd libnetconf2: update to 0.11.37
e39d52d4 libyang: update to 0.15.130
d03e32c5 treewide: fix missing/wrong MIRROR_HASH for sources from github
7c2c1cd6 luai2c: remove it for missing sources
a0831458 perl-text-csv_xs: update to 1.36
28d488f7 Merge pull request #6368 from neheb/patch-15
9e5d0b54 Merge pull request #6276 from diizzyy/utils-dbus
272974ae gammu: update lazy depend
45295846 Merge pull request #6333 from micmac1/php7-mysqlnd
b5b604f9 Merge pull request #6366 from neheb/patch-14
bacba85c Merge pull request #6372 from jefferyto/golang-compile-arguments
6a6a1e9e rtl-sdr: fix build when GCC decides not to emit inlines
2fa8e650 golang: Download bootstrap source directly, use golang-specific mirrors
35690dd4 Merge pull request #6356 from aparcar/prom-0.16
75f04994 ffmpeg/libx264: Replacing YASM with NASM and fixing ffmpeg/x264 module dependency
94f88d3d mariadb: convert init script to procd
f8368276 mariadb: add convenience symlinks
cbc23537 mariadb: fix mysql_config
4d6829f0 mariadb: add plugins
c9033324 mariadb: bump to 10.2.x release
0870b149 unrar: Update to 5.6.5
50ce6735 bind: Explicitly disable libatomic support (#6375)
de9f3656 prometheus-node-exporter-lua: adapt 0.16 metrics
c3864f53 haproxy: Update HAProxy to v1.8.12 - Update haproxy download URL and hash
5a2d77cc Merge pull request #6374 from luizluca/sane-fix_libusb
c4a25df0 sane-backends: fix libusb dependency
0768374b acme: Not all fields should be mandatory in Luci
e8adf630 golang: Allow additional arguments when compiling Go packages
06dbce29 seafile-server: avoid error creating superuser
1fe8bc94 Merge pull request #6352 from EricLuehrsen/unbound_20180625
19292650 golang: update to 1.10.3, add mirrors
21864670 unbound: limit outside script source to init funciton scope
9493e27e unbound: clean up domain periods and unnecessary quotes
36f9f95d gnupg: Update to 1.4.23
fa30d476 Merge pull request #6347 from dwmw2/domoticz
e2e11fbb Merge pull request #6062 from cotequeiroz/usbip-remove_patches
1e8db5b3 Merge pull request #6355 from Ansuel/jasson
91c6f4f8 python-mysql: upgrade to 1.3.12
26035630 haproxy: Update HAProxy to v1.8.11 - Update haproxy download URL and hash
d4db2ea7 jansson: bump to latest stable
b3eb0d23 tor: update to 0.3.3.7
482d87f2 Merge pull request #6343 from nxhack/bump_62_1
ffdbc7a6 Merge pull request #6342 from jefferyto/python-packages-update
d8521b50 domoticz: update to 4.9700 stable release, enable Python, fix compression
de8e819f Merge pull request #6344 from yousong/ssh-alt
1e07e684 openssh: let opkg manage openssh symlinks of ssh, scp
d66f3a6c icu: update to 62.1
4269a8b8 twisted: update to 18.4.0, refresh patches
04217870 php7: add package dependency on zoneinfo-core
2b749fd5 Merge pull request #6253 from neheb/patch-14
88a43560 Merge pull request #6293 from neheb/patch-16
cfe47aa1 Merge pull request #6337 from EricLuehrsen/unbound_173
a8c87eb1 python-zope-interface: update to 4.5.0
6d733be8 python-pyasn1: update to 0.4.3
e977641b python-ply: update to 3.11
9645c2fa python-ipaddress: update to 1.0.22
76ccf6c5 python-hyperlink: update to 18.0.0
6e0c9974 python-automat: update to 0.7.0, refresh patches
1cede43a python-attrs: update to 18.1.0
f332d68c haproxy: Update HAProxy to v1.8.10 - Update haproxy download URL and hash
9e97da85 Merge pull request #6248 from diizzyy/patch-1
65b01bb7 pyjwt: add new package
441e270e python-oauthlib: add new package
d53997d5 python-requests-oauthlib: add new package
1f74df5b python-certifi: add new package
01d9b705 python-requests: add new package
2f6a9999 python-qrcode: add new package
c6ce18f2 django-webpack-loader: add new package
ac62fb61 django-ranged-response: add new package
84afee13 django-simple-captcha: add new package
d9ad4b14 django-formtools: add new package
6a2239cb unbound: update to 1.7.3
f2ef6098 ola: enable and ship web stuff
c5012d67 seafile-ccnet: fixed deprecated API patch
f6e06384 php7: use mysqlnd
ecf1e741 git: update to 2.18.0
c05f2e8b seafile-seahub: added new python dependencies
05f89095 seafile-server: Fix SystemInfo table in sqlite db.
f4ee5ce0 pulseaudio: enable parallel build
82eed873 pulseaudio: update to 12.0
c8c1841a Merge pull request #6306 from aparcar/fancy_release
c10b5a3f ola: implement Host/Install for ola_protoc_plugin
cafab6d3 freetype: Update to 2.9.1
abdbf502 ola: update to 0.10.6, fix build with recent protobuf
b157cf4f Merge pull request #6098 from xavifr/b-snmp-add-extend
b23d146b Merge pull request #6064 from nxhack/fix_arm_arch_detection
fd6fd08e qemu: package qemu-nbd
b3c428cc qemu: package qemu-img
9930c3bf Merge pull request #6307 from diizzyy/sound-fdk-aac
eac2e12a gptfdisk: add a new package
7abd90e2 Merge pull request #6317 from zhaojh329/libuwsc
b21b2ebb Merge pull request #6308 from zhaojh329/rtty
f498829e libuwsc: Update to 2.0.4
04bfcfd2 tmux: Add path to global conf file
9b85c179 rtty: Update to 5.1.0
0a264360 Merge pull request #6289 from Ansuel/nginxpack
83c2603c sound/fdk-aac: Clean up Makefile, add overflow patch
2d022c61 Merge pull request #5681 from neheb/sispmctl
e40e9fc6 Merge pull request #6303 from MikePetullo/dovecot
99158896 Merge pull request #6302 from Ansuel/uwsgi-su
fc44f87d prometheus-node-exporter-lua: handle fancy release
9fff2373 dovecot: explicitly disable use of sodium
870ebb1b Merge pull request #6299 from jsmcconn/fix-avahi-runtime-dir
05299677 uwsgi-cgi: improve uwsgi configuration
3c355985 Merge pull request #6300 from jsmcconn/fix-lvm2-rundir
93c6d0fa Merge pull request #6290 from Ansuel/uwsgi-su
ecfc219c Merge pull request #6292 from cotequeiroz/nut_openssl-1.1
eebe0248 lvm2: use explicit run/lock dir defaults
933037e9 avahi: patch systemd runtime_dir change in 0.7
8704bba6 tinc: version bump 1.0.34
19c8c318 Merge pull request #6244 from neheb/patch-8
16d6d1c7 Merge pull request #6298 from neheb/patch-18
fa04f806 Merge pull request #6297 from neheb/patch-15
bb351c93 cryptsetup: Update to 2.0.3
c4961425 glpk: Update to 4.65
12248547 Merge pull request #6254 from neheb/patch-15
32c3d8a8 Merge pull request #6294 from zhaojh329/rtty
c89dc49d uwsgi: add luci-support package
41955616 nginx: add luci-support package
1512f4d9 Merge pull request #6295 from zhaojh329/libuwsc
29a46cff Merge pull request #6296 from cotequeiroz/rp-pppoe-glibc
e40d67a4 rp-pppoe: redo glibc patch
5d2751ab rtty: Update to 5.0.2
17acf042 libuwsc: update to 2.0.3
2e030a7b bind: update PKG_LICENSE to reflect upstream change
037f1def bind: Update to version 9.11.3 and optionally support eddsa for dnssec
42fe9700 libgee: Update to 0.20.1
996773d3 Merge pull request #5825 from neheb/alpine
05bf36f7 Merge pull request #6204 from cretingame/master
69882100 diffutils: fix 'compilation error on x86_64
fbffa348 Merge pull request #6284 from EricLuehrsen/unbound_zones
2e2129e5 Merge pull request #6266 from neheb/patch-18
41c150b8 Merge pull request #6264 from neheb/patch-16
5a56e39f erlang: update to version 19.3, add packages
4c459cf7 Merge pull request #6283 from neheb/patch-4
a7fd6923 unbound: improve local zone evaluation in UCI
d6e7f64a unbound: update to 1.7.2
7716f410 Merge pull request #6268 from pprindeville/dhcp-update-resolv.conf
29934469 zmq: Update to 4.1.6
86d0ba60 file: Disable libseccomp by default
db6adb61 isc-dhcp: write resolv.conf per network & dhcp settings
da9ace7d lzmq: Update to 0.4.4
113a3478 dbus: Update to 1.12.8
302454f5 seafile-server: bump to 6.3.0
84856c27 pkg-config: Update to 0.29.2
cc152703 yunbridge: Swich to 1.6.0
bb1543e8 libnetfilter-acct: Update to 1.0.3
cd38fe42 libstrophe: Update to 0.9.2
c52c0376 gawk: Update to 4.2.1
daaa9015 esniper: Update to 2.33.0
c235c21a apr-util: Update to 1.6.1
ae756a71 openldap: Switch tarball sources to https and http
58492c41 hdparm: Update to 9.56
48640b38 opensc: Update to 0.18.0
dc469653 dhcpcd: bump to 7.0.5
89f4a3f2 sysstat: bump to 11.6.4
beedb40d zsh: Update to 5.5.1
82cc7c4e apr: Update to 1.6.3
7fca11ff acpid: Update to 2.0.29
b211914f zabbix: Bump to latest version
21568764 seafile-seahub: bump to 6.3.0
113ab036 seafile-ccnet: bump to 6.3.0
9a9871e4 libsearpc: bump to version 3.0.8
633fe0db usbip: adapt package to new kernel/libudev
a565ef8e SNMPD: Add snmp_extend config option
ddbcdf8b sispmctl: Change URL to HTTPS
a553b780 alpine: Update to 2.21.999 and update URLS
3482320c node: Fix incorrect detection of arm_version and arm_fpu
0baaabb6 usbip: Remove obsolete patches